### ISSUE TITLE
On Creation of new password file, prompt doesnt allow me to retype new pass

### ISSUE THREAD

**Issue by jdalrymple** [http-auth/htdigest#1]
htdigest -c Testfile "Private Area" username (I then click enter)
New password: test (enter again)

Retype new password:

Pasword verification error.
(click enter again)
_Exits_

I noticed you dont have prompt.start above your prompt.get function. Could this be the cause of the issue?

**Comment by gevorg** [comment]
htdigest -c Testfile "Private Area" username

New password: test
Re-type new password:test
Adding password for user username in realm Private Area.

**Comment by gevorg** [comment]
Sorry, I can't see what is the problem in do you retype password correctly ?

**Comment by jdalrymple** [comment]
I can't even enter the repassword. After I type in password and click enter, it
simply jumps to password verification error.

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.4.10&pv=6.0&source=email_footer_2] On Fri, Oct 16, 2015 at 5:56 PM, Gevorg Harutyunyan < notifications@github.com [notifications@github.com] > wrote:
Sorry, I can't see what is the problem in do you retype password correctly ?

—
Reply to this email directly or view it on GitHub
[https://github.com/gevorg/htdigest/issues/1#issuecomment-148845733] .[https://github.com/notifications/beacon/ADkfrpqQqv_rPE9LWzkyQ-a5dkK2f7Ymks5o8WoSgaJpZM4GQaBU.gif]

**Comment by jdalrymple** [comment]
Its the same error mikeRead is having

**Comment by gevorg** [comment]
Thanks for reporting, I just checked this issue and it seems to happen with new node.js version only. The problem appears also for https://github.com/flatiron/prompt module that I have used and also https://github.com/isaacs/read alternative module. So for now I cannot fix this issue, til these modules will not work properly as I depend on them. Gevorg

**Comment by jdalrymple** [comment]
Yea I noticed that as well. I begun debugging prompt but have made only a
little headway.

**Comment by gevorg** [comment]
Well, I didn't fix issue, because it shows/hides input randomly. But at-least now it allows you to type password/repeat it.
